server:
  port: 7001

spring:
  application:
    name: cloud_eureka_server

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  #注册自己
#      defaultZone: http://eureka7002.com:7002/eureka/