server:
  port: 8003
spring:
  application:
    name: Payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT
    username: root
    password: 19980120

  cloud:
    zookeeper:
      connect-string: localhost:2181

# 配置zookeeper


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sofency.top.entities