server:
  port: 80

spring:
  application:
    name: Order

eureka:
  client:
    register-with-eureka: true  #标识是否将自己注册到注册中心
    fetch-registry: true #是否从注册中心抓取已有的注册信息  单节点 没有必要 集群必须配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #将服务注册到注册中心中